title: WapiFirma Documentacion
description: Sitio de documentacion para WapiFirma
theme: just-the-docs
color-scheme: wapi


url: https://wapifi-firma.github.io

aux_links:
  App WapiFirma: https://app.wapifirma.com


##Branding##
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"



##Sidebar##
nav_enabled: true
