title: WapiFirma Documentacion
description: Sitio de documentacion para WapiFirma
email: hola@wapifirma.com

url: "https://wapifirma.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: wapi-firma/documentation # for github-metadata

twitter_username: openfn
github_username:  openfn
aux_links:
  "App Wapifirma":
    - "//app.wapifirma.com/"
    


logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"


# Build settings
theme: "just-the-docs"
#remote_theme: pmarsceill/just-the-docs
color_scheme: wapi


# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
