title: WapiFirma Documentacion
description: Sitio de documentacion para WapiFirma
email: hola@wapifirma.com

url: "https://wapifirma.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: wapi-firma/documentation # for github-metadata

twitter_username: openfn
github_username:  openfn
aux_links:
  "GoData on GitHub":
    - "//github.com/WorldHealthOrganization/godata/"
  "Community of Practice":
    - "//community-godata.who.int/"
    


logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"


# Build settings
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
color_scheme: wapi


# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/WorldHealthOrganization/godata" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: "docs" # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
